# Generated by Django 3.2.6 on 2021-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=100)),
                ('rotas', models.CharField(choices=[('A. Voador / Xipamanine', 'A. Voador / Xipamanine'), ('Museu / P. Combatentes', 'Museu / P. Combatentes'), ('Matola Gar / Magoanini', 'Matola Gar / Magoanini'), ('Nkobe / Baixa', 'Nkobe / Baixa')], default='A. Voador / Xipamanine', max_length=40)),
                ('data_do_incidente', models.DateField(blank=True)),
                ('tipo_de_infracao', models.CharField(choices=[('Condução sob efeito de Alcool', 'Condução sob efeito de alcool'), ('Excesso de Velocidade', 'Excesso de velocidade'), ('Superlotação', 'Superlotação')], default='Condução sob efeito de Alcool', max_length=50)),
                ('limpeza_do_carro', models.CharField(choices=[('Limpo', 'Limpo'), ('Aceitavel', 'ACEITAVEL'), ('Sujo', 'Sujo'), ('Muito Sujo', 'Muito Sujo')], default='Limpo', max_length=20)),
                ('observacoes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Infocar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=30)),
                ('cor_da_viatura', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
